name: Syntax Check All Scripts and YAML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Bash scripts
      - name: Check Bash scripts
        run: |
          find . -type f -name "*.sh" -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file..."
            bash -n "$file"
          done

      # Python scripts
      - name: Check Python scripts
        run: |
          find . -type f -name "*.py" -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file..."
            python -m py_compile "$file"
          done

      # PHP scripts
      - name: Check PHP scripts
        run: |
          find . -type f -name "*.php" -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file..."
            php -l "$file"
          done

      # YAML files
      - name: Check YAML syntax
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) -print0 | while IFS= read -r -d '' file; do
            echo "Linting $file..."
            yamllint "$file"
          done
